package vista;

import controlador.bdMetodos;
import modelo.Comidas;
import modelo.Bebidas;
import static java.awt.Color.*;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jonah
 */
public class Agregar extends javax.swing.JPanel {
    
    boolean validacionCategoria = false;
    boolean validacionNombre = false;    
    boolean validacionPrecio = false;    
    boolean validacionStock = false;   
    File imag;
    byte[] fileBytes;
    
    bdMetodos m1 = new bdMetodos();
    
    
    public Agregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelIDvalidar = new javax.swing.JLabel();
        jLabelcategoriavalidar = new javax.swing.JLabel();
        jLabelnombrevalidar = new javax.swing.JLabel();
        jLabelpreciovalidar = new javax.swing.JLabel();
        jLabelstockvalidar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBoxCategoría = new javax.swing.JComboBox<>();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldStock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonValidar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(0, 0, 102));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Se agregó un producto de la base de datos");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("¡Nuevo Cambio!");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel9))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel9)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFormattedTextField1.setText("jFormattedTextField1");

        jPanel1.setBackground(new java.awt.Color(14, 14, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabelIDvalidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 118, -1, -1));
        jPanel1.add(jLabelcategoriavalidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, 30));
        jPanel1.add(jLabelnombrevalidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, 30));
        jPanel1.add(jLabelpreciovalidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));
        jPanel1.add(jLabelstockvalidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 356, -1, 30));

        jPanel3.setBackground(new java.awt.Color(4, 4, 23));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(4, 4, 23));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 102), new java.awt.Color(102, 0, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 102)));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" AGREGAR PRODUCTO");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/agregar_producto.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 780, 70));

        jLabel10.setBackground(new java.awt.Color(102, 102, 255));
        jLabel10.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo_jframe_1.jpg"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 90));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 90));

        jPanel14.setBackground(new java.awt.Color(4, 4, 23));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INGRESE LOS DATOS DEL PRODUCTO");
        jPanel14.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 520, 70));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 850, 70));

        jPanel10.setBackground(new java.awt.Color(8, 8, 36));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CATEGORIA DEL PRODUCTO");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 28));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOMBRE DEL PRODUCTO");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 24));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRECIO DEL PRODUCTO");
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 203, 25));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("STOCK DEL PRODUCTO");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 170, 30));

        jSeparator1.setBackground(new java.awt.Color(5, 5, 61));
        jSeparator1.setForeground(new java.awt.Color(5, 5, 61));
        jPanel10.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, 20));

        jSeparator2.setBackground(new java.awt.Color(5, 5, 61));
        jSeparator2.setForeground(new java.awt.Color(5, 5, 61));
        jPanel10.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 20));

        jSeparator3.setBackground(new java.awt.Color(50, 5, 61));
        jSeparator3.setForeground(new java.awt.Color(56, 5, 61));
        jPanel10.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, 20));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 270, 400));

        jComboBoxCategoría.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCategoría.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida", "Comida" }));
        jComboBoxCategoría.setSelectedIndex(-1);
        jComboBoxCategoría.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoríaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCategoría, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 145, 30));

        jTextFieldNombre.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 145, 30));

        jTextFieldPrecio.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N
        jTextFieldPrecio.setBorder(null);
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });
        jTextFieldPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 145, 30));

        jTextFieldStock.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N
        jTextFieldStock.setBorder(null);
        jTextFieldStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStockKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 145, 30));

        jLabel2.setBackground(new java.awt.Color(7, 7, 28));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Para agregar un producto necesita validar primero.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 480, -1));

        jPanel2.setBackground(new java.awt.Color(3, 3, 29));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonValidar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonValidar.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonValidar.setText("Validar");
        jButtonValidar.setBorder(null);
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 26, 113, 41));

        jButtonLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setBorder(null);
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 26, 111, 40));

        jButtonAgregar.setBackground(new java.awt.Color(102, 255, 102));
        jButtonAgregar.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(0, 51, 0));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 51, 0), null, new java.awt.Color(0, 51, 0)));
        jButtonAgregar.setVisible(false);
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 26, 117, 40));

        jLabel13.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("LIMPIAR DATOS:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 39, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("VALIDAR DATOS: ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 37, 140, 20));

        jLabel14.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("AGREGAR PRODUCTO:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 39, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 850, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        
        
        if(jComboBoxCategoría.getSelectedItem () != null){
        
            jLabelcategoriavalidar.setText("La Categoría es correcta");
            jLabelcategoriavalidar.setForeground(green);
            validacionCategoria = true;
        
        } else {
        
            jLabelcategoriavalidar.setText("Debe elegir una categoría válida");
            jLabelcategoriavalidar.setForeground(red);
            validacionCategoria = false;
            
        }
        
        if(!jTextFieldNombre.getText().isEmpty()) {
        
            jLabelnombrevalidar.setText("El nombre es válido");
            jLabelnombrevalidar.setForeground(green);           
            validacionNombre = true;
            
        } else {
        
            jLabelnombrevalidar.setText("Ingrese un nombre válido");
            jLabelnombrevalidar.setForeground(red);
            validacionNombre = false;            

        }
        
         if(!jTextFieldPrecio.getText().isEmpty()) {
        
            jLabelpreciovalidar.setText("El precio es válido");
            jLabelpreciovalidar.setForeground(green);           
            validacionPrecio = true;
         
        } else {
        
            jLabelpreciovalidar.setText("Ingrese un precio válido");
            jLabelpreciovalidar.setForeground(red);
              validacionPrecio = false;
              
        }
         
         if(!jTextFieldStock.getText().isEmpty()) {
        
            jLabelstockvalidar.setText("El stock es válido");
            jLabelstockvalidar.setForeground(green);           
            validacionStock = true;
            
        } else {
        
            jLabelstockvalidar.setText("Ingrese un stock válido");
            jLabelstockvalidar.setForeground(red);
            validacionStock = false;
            
         }        
         
         if(validacionCategoria && validacionNombre && validacionPrecio && validacionStock ==true){
         
             jButtonAgregar.setVisible(true);
             jLabel2.setText("Deberá seleccionar una imagen al momento de agregar los datos*");
         
         } else {
         
             jButtonAgregar.setVisible(false);
             
         }
        
    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        jButtonAgregar.setVisible(false);
        jComboBoxCategoría.setSelectedIndex(-1);
        jTextFieldNombre.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldStock.setText("");
        
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
         
        JFileChooser fch = new JFileChooser();
        fch.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filtro1 = new FileNameExtensionFilter("*.PNG", "png");
        fch.setFileFilter(filtro1);
        int seleccion = fch.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION) {

            imag = fch.getSelectedFile();
        
        try (FileInputStream fis = new FileInputStream(imag);
             ByteArrayOutputStream bos = new ByteArrayOutputStream()) {

            byte[] buffer = new byte[1024];
            int bytesRead;

            while ((bytesRead = fis.read(buffer)) != -1) {
                bos.write(buffer, 0, bytesRead);
            }

            fileBytes = bos.toByteArray();
        }   catch (FileNotFoundException ex) {
                Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
        String item = String.valueOf(jComboBoxCategoría.getSelectedItem());
        String nomb = jTextFieldNombre.getText(); 
        int prec =  Integer.parseInt(jTextFieldPrecio.getText());
        int stock = Integer.parseInt(jTextFieldStock.getText());
        
        if(item=="Bebida"){
        
            Bebidas bebida1 = new Bebidas(item, nomb, prec, stock, fileBytes);
            bebida1.imprimir();
            m1.Agregar(bebida1);
            jDialog1.setSize(464, 340);
            jDialog1.setLocation(600, 300);
            jDialog1.show();
            
        } else if(item=="Comida") {
        
            Comidas comida1 = new Comidas(item, nomb, prec, stock, fileBytes);
            comida1.imprimir();
            m1.Agregar(comida1);
            jDialog1.setSize(464, 340);
            jDialog1.setLocation(600, 300);
            jDialog1.show();
        }
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jTextFieldStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockKeyTyped

        char k2 = evt.getKeyChar();

        if(!Character.isDigit(k2)) {

            evt.consume();

        }

    }//GEN-LAST:event_jTextFieldStockKeyTyped

    private void jTextFieldPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioKeyTyped

        char k1 = evt.getKeyChar();

        if(!Character.isDigit(k1)) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldPrecioKeyTyped

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jComboBoxCategoríaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoríaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoríaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JComboBox<String> jComboBoxCategoría;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIDvalidar;
    private javax.swing.JLabel jLabelcategoriavalidar;
    private javax.swing.JLabel jLabelnombrevalidar;
    private javax.swing.JLabel jLabelpreciovalidar;
    private javax.swing.JLabel jLabelstockvalidar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldStock;
    // End of variables declaration//GEN-END:variables
}
