/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.bdMetodos;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import modelo.Producto;

/**
 *
 * @author jonah
 */
public class Eliminar extends javax.swing.JPanel {

        Producto p3; 
    
       bdMetodos m3 = new bdMetodos();
       
    /**
     * Creates new form Eliminar
     */
    public Eliminar() {
        initComponents();
        this.texto_eliminar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogEliminarPantalla = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabelVerImg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabelCateg = new javax.swing.JLabel();
        jLabelNomb = new javax.swing.JLabel();
        jLabelPrec = new javax.swing.JLabel();
        jLabelStock = new javax.swing.JLabel();
        jLabelImg = new javax.swing.JLabel();
        texto_eliminar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jButtonEliminar = new javax.swing.JButton();
        jTextFieldCateg = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldStock = new javax.swing.JTextField();
        jButtonVerImg = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTextFieldID = new javax.swing.JTextField();
        jButtonBuscarDatos = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Se eliminó un producto de la base de datos");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¡Nuevo Cambio!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogEliminarPantallaLayout = new javax.swing.GroupLayout(jDialogEliminarPantalla.getContentPane());
        jDialogEliminarPantalla.getContentPane().setLayout(jDialogEliminarPantallaLayout);
        jDialogEliminarPantallaLayout.setHorizontalGroup(
            jDialogEliminarPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogEliminarPantallaLayout.setVerticalGroup(
            jDialogEliminarPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVerImg, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVerImg, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(14, 14, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(4, 4, 32));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCateg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCateg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCateg.setText("CATEGORIA DEL PRODUCTO");
        jLabelCateg.setVisible(false);
        jPanel7.add(jLabelCateg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 29));

        jLabelNomb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNomb.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomb.setText("NOMBRE DEL PRODUCTO");
        jLabelNomb.setVisible(false);
        jPanel7.add(jLabelNomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, 29));

        jLabelPrec.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelPrec.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrec.setText("PRECIO DEL PRODUCTO");
        jLabelPrec.setVisible(false);
        jPanel7.add(jLabelPrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 170, 29));

        jLabelStock.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelStock.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStock.setText("STOCK DEL PRODUCTO");
        jLabelStock.setVisible(false);
        jPanel7.add(jLabelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 29));

        jLabelImg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelImg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImg.setText("IMAGEN DEL PRODUCTO");
        jLabelImg.setVisible(false);
        jPanel7.add(jLabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, 29));

        texto_eliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        texto_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        texto_eliminar.setText("ELIMINAR PRODUCTO");
        jPanel7.add(texto_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(5, 5, 61));
        jSeparator1.setForeground(new java.awt.Color(5, 5, 61));
        jPanel7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, 20));

        jSeparator2.setBackground(new java.awt.Color(5, 5, 61));
        jSeparator2.setForeground(new java.awt.Color(5, 5, 61));
        jPanel7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 180, 20));

        jSeparator3.setBackground(new java.awt.Color(60, 5, 61));
        jSeparator3.setForeground(new java.awt.Color(49, 5, 61));
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 20));

        jSeparator4.setBackground(new java.awt.Color(5, 5, 61));
        jSeparator4.setForeground(new java.awt.Color(5, 5, 61));
        jPanel7.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 20));

        jSeparator5.setBackground(new java.awt.Color(60, 5, 61));
        jSeparator5.setForeground(new java.awt.Color(54, 5, 61));
        jPanel7.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, 20));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, 380));

        jPanel4.setBackground(new java.awt.Color(8, 8, 42));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEliminar.setBackground(new java.awt.Color(255, 102, 102));
        jButtonEliminar.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(51, 0, 0));
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 0), new java.awt.Color(51, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        jButtonEliminar.setVisible(false);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 120, 40));

        jTextFieldCateg.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jTextFieldCateg.setEnabled(false);
        jTextFieldCateg.setVisible(false);
        jTextFieldCateg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCategKeyTyped(evt);
            }
        });
        jPanel4.add(jTextFieldCateg, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 120, 30));

        jTextFieldNombre.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jTextFieldNombre.setEnabled(false);
        jTextFieldNombre.setVisible(false);
        jPanel4.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 120, 30));

        jTextFieldPrecio.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jTextFieldPrecio.setEnabled(false);
        jTextFieldPrecio.setVisible(false);
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });
        jTextFieldPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioKeyTyped(evt);
            }
        });
        jPanel4.add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 120, 30));

        jTextFieldStock.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jTextFieldStock.setEnabled(false);
        jTextFieldStock.setVisible(false);
        jTextFieldStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStockActionPerformed(evt);
            }
        });
        jTextFieldStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldStockKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStockKeyTyped(evt);
            }
        });
        jPanel4.add(jTextFieldStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 120, 30));

        jButtonVerImg.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVerImg.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonVerImg.setText("Ver");
        jButtonVerImg.setVisible(false);
        jButtonVerImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerImgActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonVerImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 120, 35));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 440, 380));

        jPanel8.setBackground(new java.awt.Color(4, 4, 23));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 102), new java.awt.Color(102, 0, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 102)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ELIMINAR PRODUCTO");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 280, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/eliminar_producto.png"))); // NOI18N
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 70));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 780, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo_jframe_1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 90));

        jPanel6.setBackground(new java.awt.Color(4, 4, 23));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INGRESA LA ID DEL PRODUCTO PARA ELIMINAR");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 850, 70));

        jPanel9.setBackground(new java.awt.Color(4, 4, 23));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 102), new java.awt.Color(102, 0, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 102)));

        jTextFieldID.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jTextFieldID.setBorder(null);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        jTextFieldID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDKeyTyped(evt);
            }
        });

        jButtonBuscarDatos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscarDatos.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonBuscarDatos.setText("Buscar");
        jButtonBuscarDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 102), new java.awt.Color(102, 0, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 102)));
        jButtonBuscarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarDatosActionPerformed(evt);
            }
        });

        jButtonVolver.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.setVisible(false);
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jLabelID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID.setText("ID DEL PRODUCTO");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 650, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed

    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextFieldIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDKeyTyped

        char k1 = evt.getKeyChar();

        if(!Character.isDigit(k1)) {

            evt.consume();

        }

    }//GEN-LAST:event_jTextFieldIDKeyTyped

    private void jButtonBuscarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarDatosActionPerformed

         int idBus = Integer.parseInt(jTextFieldID.getText());
        
        p3 = m3.Seleccionar(idBus);
         
        jTextFieldCateg.setText(p3.getCategoriaProducto());
        jTextFieldNombre.setText(p3.getNombreProducto());
        jTextFieldPrecio.setText(String.valueOf(p3.getPrecioProducto()));
        jTextFieldStock.setText(String.valueOf(p3.getCantidadProducto()));
        
        jTextFieldID.setEnabled(false);
        jButtonVolver.setVisible(true);
        jLabelCateg.setVisible(true);
        jTextFieldCateg.setVisible(true);
        jLabelNomb.setVisible(true);
        jTextFieldNombre.setVisible(true);
        jLabelPrec.setVisible(true);
        jTextFieldPrecio.setVisible(true);
        jLabelStock.setVisible(true);
        jTextFieldStock.setVisible(true);
        jLabelImg.setVisible(true);
        jButtonVerImg.setVisible(true);
        jButtonEliminar.setVisible(true);
        this.texto_eliminar.setVisible(true);

    }//GEN-LAST:event_jButtonBuscarDatosActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed

        jTextFieldID.enable(true);
        jTextFieldID.setText("");
        jButtonVolver.setVisible(false);
        jLabelCateg.setVisible(false);
        jTextFieldCateg.setVisible(false);
        jLabelNomb.setVisible(false);
        jTextFieldNombre.setVisible(false);
        jLabelPrec.setVisible(false);
        jTextFieldPrecio.setVisible(false);
        jLabelStock.setVisible(false);
        jTextFieldStock.setVisible(false);
        jLabelImg.setVisible(false);
        jButtonVerImg.setVisible(false);
        this.texto_eliminar.setVisible(false);
        jButtonEliminar.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jTextFieldPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioKeyPressed
        jButtonEliminar.setVisible(false);
    }//GEN-LAST:event_jTextFieldPrecioKeyPressed

    private void jTextFieldPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioKeyTyped

        
    }//GEN-LAST:event_jTextFieldPrecioKeyTyped

    private void jTextFieldStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStockActionPerformed

    }//GEN-LAST:event_jTextFieldStockActionPerformed

    private void jTextFieldStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockKeyPressed

    }//GEN-LAST:event_jTextFieldStockKeyPressed

    private void jTextFieldStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockKeyTyped

        

    }//GEN-LAST:event_jTextFieldStockKeyTyped

    private void jButtonVerImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerImgActionPerformed
        byte[] imageBytes =p3.getImagen();
        ImageIcon imageIcon = null;
        try {
            ByteArrayInputStream bais = new ByteArrayInputStream(imageBytes);
            BufferedImage imagen = ImageIO.read(bais);
            imageIcon = new ImageIcon(imagen);
        } catch (IOException e) {
            System.out.println("Error: " + e);
        }
        jDialog1.setSize(551, 387);
        jDialog1.setLocation(600, 300);
        jDialog1.show();
        jLabelVerImg.setIcon(imageIcon); 
                
                
    }//GEN-LAST:event_jButtonVerImgActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed

        m3.Eliminar_Producto(p3.getIdProducto());
        
        jDialogEliminarPantalla.setSize(464, 340);
        jDialogEliminarPantalla.setLocation(600, 300);
        jDialogEliminarPantalla.show();
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTextFieldCategKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCategKeyTyped

    }//GEN-LAST:event_jTextFieldCategKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarDatos;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonVerImg;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialogEliminarPantalla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCateg;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JLabel jLabelNomb;
    private javax.swing.JLabel jLabelPrec;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JLabel jLabelVerImg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextFieldCateg;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldStock;
    private javax.swing.JLabel texto_eliminar;
    // End of variables declaration//GEN-END:variables
}
