/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.bdMetodos;

/**
 *
 * @author usuar
 */
public class InicioSesion extends javax.swing.JPanel {
int intentos = 3;
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
       
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        MENSAJE_INTENTOS_INICIO = new javax.swing.JLabel();
        CAJA_CONTRASEÑA_ADMIN_USUARIO = new javax.swing.JPasswordField();
        CAJA_NOMBRE_ADMIN = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        INICIAR_SESSION_ADMIN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(865, 617));

        jPanel1.setBackground(new java.awt.Color(101, 118, 219));
        jPanel1.setPreferredSize(new java.awt.Dimension(865, 617));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Eras Bold ITC", 0, 65)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 204));
        jLabel13.setText("DUOC UC");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 320, 60));

        jLabel12.setBackground(new java.awt.Color(204, 153, 255));
        jLabel12.setFont(new java.awt.Font("Eras Bold ITC", 1, 75)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 255));
        jLabel12.setText("CASINO ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 340, 70));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Eras Bold ITC", 0, 65)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(149, 99, 245));
        jLabel8.setText("DUOC UC");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 330, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icono.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 490, -1));

        jLabel7.setBackground(new java.awt.Color(204, 153, 255));
        jLabel7.setFont(new java.awt.Font("Eras Bold ITC", 1, 75)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(122, 122, 245));
        jLabel7.setText("CASINO ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 340, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/inicio_session_.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 450, 710));

        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MENSAJE_INTENTOS_INICIO.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MENSAJE_INTENTOS_INICIO.setText("¡Solamente tiene 3 intentos para iniciar sesión!");
        jPanel4.add(MENSAJE_INTENTOS_INICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, 24));

        CAJA_CONTRASEÑA_ADMIN_USUARIO.setFont(new java.awt.Font("Eras Bold ITC", 0, 11)); // NOI18N
        CAJA_CONTRASEÑA_ADMIN_USUARIO.setText("CONTRASEÑA_ADMIN_USUARIOCAJA_CONTRASEÑCAJA_CA");
        CAJA_CONTRASEÑA_ADMIN_USUARIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CAJA_CONTRASEÑA_ADMIN_USUARIOMouseClicked(evt);
            }
        });
        CAJA_CONTRASEÑA_ADMIN_USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAJA_CONTRASEÑA_ADMIN_USUARIOActionPerformed(evt);
            }
        });
        jPanel4.add(CAJA_CONTRASEÑA_ADMIN_USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 290, 50));

        CAJA_NOMBRE_ADMIN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        CAJA_NOMBRE_ADMIN.setForeground(new java.awt.Color(102, 102, 102));
        CAJA_NOMBRE_ADMIN.setText("NOMBRE DEL USUARIO");
        CAJA_NOMBRE_ADMIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CAJA_NOMBRE_ADMINMouseClicked(evt);
            }
        });
        CAJA_NOMBRE_ADMIN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CAJA_NOMBRE_ADMINFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CAJA_NOMBRE_ADMINFocusLost(evt);
            }
        });
        CAJA_NOMBRE_ADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAJA_NOMBRE_ADMINActionPerformed(evt);
            }
        });
        CAJA_NOMBRE_ADMIN.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                CAJA_NOMBRE_ADMINTextValueChanged(evt);
            }
        });
        jPanel4.add(CAJA_NOMBRE_ADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 290, 40));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("SALIR DEL PROGRAMA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 190, 50));

        INICIAR_SESSION_ADMIN.setBackground(new java.awt.Color(0, 0, 51));
        INICIAR_SESSION_ADMIN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        INICIAR_SESSION_ADMIN.setForeground(new java.awt.Color(255, 255, 255));
        INICIAR_SESSION_ADMIN.setText("INICIAR SESIÓN");
        INICIAR_SESSION_ADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIAR_SESSION_ADMINActionPerformed(evt);
            }
        });
        jPanel4.add(INICIAR_SESSION_ADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 170, 48));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel1.setText("INICIO SESIÓN");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 290, 40));

        jLabel9.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel9.setText("INGRESE EL NOMBRE DE USUARIO");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 240, 330, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/ojo_contraseña.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/perfil_usuario.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 260, 140));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("© Duoc UC");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, -1, -1));

        jLabel10.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel10.setText("INGRESE LA CONTRASEÑA");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(111, 111, 111))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 390, 260));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 590, 600));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 690));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1320, 690));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/inicio_session_.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void INICIAR_SESSION_ADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIAR_SESSION_ADMINActionPerformed
        // TODO add your handling code here:
        bdMetodos metodo = new bdMetodos();
        metodo.InicioSession(CAJA_NOMBRE_ADMIN, CAJA_CONTRASEÑA_ADMIN_USUARIO);
        intentos = intentos - 1;
        if (intentos == 3){
             MENSAJE_INTENTOS_INICIO.setText("¡Solamente tienes "+ intentos +" intentos para iniciar sesi+ón!"); 
             MENSAJE_INTENTOS_INICIO.setForeground(new java.awt.Color(153,153,0));
        }
        else if (intentos == 2){
            
             MENSAJE_INTENTOS_INICIO.setText("¡Solamente tienes "+ intentos +" intentos para iniciar sesión!"); 
             MENSAJE_INTENTOS_INICIO.setForeground(new java.awt.Color(255,153,0));
             
        }
        else if (intentos == 1){
             MENSAJE_INTENTOS_INICIO.setForeground(new java.awt.Color(255,0,0));
             MENSAJE_INTENTOS_INICIO.setText("¡Solamente tiene "+ intentos +" intento para iniciar sesión!"); 
             
        }
        else if (intentos == 0){
            System.out.println("!INTENTOS ACABADOS¡");
            System.exit(WIDTH);
            
        }
            
    }//GEN-LAST:event_INICIAR_SESSION_ADMINActionPerformed

    private void CAJA_NOMBRE_ADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAJA_NOMBRE_ADMINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAJA_NOMBRE_ADMINActionPerformed

    private void CAJA_CONTRASEÑA_ADMIN_USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAJA_CONTRASEÑA_ADMIN_USUARIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAJA_CONTRASEÑA_ADMIN_USUARIOActionPerformed

    private void CAJA_NOMBRE_ADMINFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CAJA_NOMBRE_ADMINFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_CAJA_NOMBRE_ADMINFocusLost

    private void CAJA_NOMBRE_ADMINFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CAJA_NOMBRE_ADMINFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_CAJA_NOMBRE_ADMINFocusGained

    private void CAJA_NOMBRE_ADMINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAJA_NOMBRE_ADMINMouseClicked
        CAJA_NOMBRE_ADMIN.setText("");
        
    }//GEN-LAST:event_CAJA_NOMBRE_ADMINMouseClicked

    private void CAJA_CONTRASEÑA_ADMIN_USUARIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAJA_CONTRASEÑA_ADMIN_USUARIOMouseClicked
        CAJA_CONTRASEÑA_ADMIN_USUARIO.setText("");
        
    }//GEN-LAST:event_CAJA_CONTRASEÑA_ADMIN_USUARIOMouseClicked

    private void CAJA_NOMBRE_ADMINTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_CAJA_NOMBRE_ADMINTextValueChanged
    
    }//GEN-LAST:event_CAJA_NOMBRE_ADMINTextValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CAJA_CONTRASEÑA_ADMIN_USUARIO;
    private java.awt.TextField CAJA_NOMBRE_ADMIN;
    private javax.swing.JButton INICIAR_SESSION_ADMIN;
    public javax.swing.JLabel MENSAJE_INTENTOS_INICIO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
