/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.bdMetodos;

/**
 *
 * @author jonah
 */
public class Listar extends javax.swing.JPanel {

    /**
     * Creates new form Listar
     */
    public Listar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BOTON_PRODUCTOS = new javax.swing.JButton();
        INGRESA_LA_ID_CATEGORIA = new java.awt.TextField();
        BOTON_CATEGORIA = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(14, 14, 53));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 617));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(4, 4, 23));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(4, 4, 23));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 102), new java.awt.Color(102, 0, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 102)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LISTAR PRODUCTOS");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 260, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/listar_producto.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, -1, 90));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 780, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo_jframe_1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 830, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 840, 90));

        jPanel3.setBackground(new java.awt.Color(8, 8, 36));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, null, null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jPanel7.setBackground(new java.awt.Color(4, 4, 23));

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTAR TODOS LOS PRODUCTOS:");

        BOTON_PRODUCTOS.setBackground(new java.awt.Color(255, 255, 255));
        BOTON_PRODUCTOS.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        BOTON_PRODUCTOS.setText("PRODUCTOS");
        BOTON_PRODUCTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_PRODUCTOSActionPerformed(evt);
            }
        });

        INGRESA_LA_ID_CATEGORIA.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        INGRESA_LA_ID_CATEGORIA.setForeground(new java.awt.Color(102, 102, 102));
        INGRESA_LA_ID_CATEGORIA.setText("INGRESA LA CATEGORIA");
        INGRESA_LA_ID_CATEGORIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INGRESA_LA_ID_CATEGORIAMouseClicked(evt);
            }
        });
        INGRESA_LA_ID_CATEGORIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESA_LA_ID_CATEGORIAActionPerformed(evt);
            }
        });
        INGRESA_LA_ID_CATEGORIA.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                INGRESA_LA_ID_CATEGORIATextValueChanged(evt);
            }
        });

        BOTON_CATEGORIA.setBackground(new java.awt.Color(255, 255, 255));
        BOTON_CATEGORIA.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        BOTON_CATEGORIA.setText("CATEGORIA");
        BOTON_CATEGORIA.setBorder(null);
        BOTON_CATEGORIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_CATEGORIAActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LISTAR PRODUCTOS POR CATEGORIA:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48)
                        .addComponent(BOTON_PRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BOTON_CATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(INGRESA_LA_ID_CATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(165, 244, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(INGRESA_LA_ID_CATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BOTON_PRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(BOTON_CATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 110));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 830, 110));

        jPanel5.setBackground(new java.awt.Color(4, 4, 23));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 102), new java.awt.Color(102, 0, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 102)));

        TABLA.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        TABLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                " ", " ", "  ", " "
            }
        ));
        TABLA.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(TABLA);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 810, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BOTON_PRODUCTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_PRODUCTOSActionPerformed
        bdMetodos metodo  = new bdMetodos();
        metodo.Listar_Producto(TABLA);
        
    }//GEN-LAST:event_BOTON_PRODUCTOSActionPerformed

    private void INGRESA_LA_ID_CATEGORIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESA_LA_ID_CATEGORIAActionPerformed
        
    }//GEN-LAST:event_INGRESA_LA_ID_CATEGORIAActionPerformed

    private void BOTON_CATEGORIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_CATEGORIAActionPerformed
        bdMetodos metodo = new bdMetodos ();
        
        metodo.Listar_Categoria(INGRESA_LA_ID_CATEGORIA,TABLA);
        
    }//GEN-LAST:event_BOTON_CATEGORIAActionPerformed

    private void INGRESA_LA_ID_CATEGORIATextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_INGRESA_LA_ID_CATEGORIATextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_INGRESA_LA_ID_CATEGORIATextValueChanged

    private void INGRESA_LA_ID_CATEGORIAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INGRESA_LA_ID_CATEGORIAMouseClicked
        INGRESA_LA_ID_CATEGORIA.setText("");
    }//GEN-LAST:event_INGRESA_LA_ID_CATEGORIAMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTON_CATEGORIA;
    private javax.swing.JButton BOTON_PRODUCTOS;
    private java.awt.TextField INGRESA_LA_ID_CATEGORIA;
    private javax.swing.JTable TABLA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
