/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.bdMetodos;
import static java.awt.Color.green;
import static java.awt.Color.red;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import modelo.*;

/**
 *
 * @author jonah
 */
public class Modificar extends javax.swing.JPanel {

    boolean validacionNombre = false;
    boolean validacionPrecio = false;    
    boolean validacionStock = false;
   
    Producto p1;
    
   bdMetodos m2 = new bdMetodos();
    
    public Modificar() {
        initComponents();
        this.TEXTO_MODIFICAR_PRODUCTO.setVisible(false);
        this.TEXTO_LIMPIAR_DATOS.setVisible(false);
        this.TEXTO_VALIDAR_dATOS.setVisible(false);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        Fondo1 = new javax.swing.JPanel();
        jLabelVerImgD = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabelPrecioValidar = new javax.swing.JLabel();
        jLabelStockValidar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelvalidacionNombre = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelCateg = new javax.swing.JLabel();
        jLabelNomb = new javax.swing.JLabel();
        jLabelPrec = new javax.swing.JLabel();
        jLabelStock = new javax.swing.JLabel();
        jLabelImg = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        TEXTO_MODIFICAR_PRODUCTO = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButtonBuscarDatos = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jButtonVolver = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jTextFieldCateg = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldStock = new javax.swing.JTextField();
        jButtonVer = new javax.swing.JButton();
        jButtonValidar = new javax.swing.JButton();
        TEXTO_VALIDAR_dATOS = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();
        TEXTO_LIMPIAR_DATOS = new javax.swing.JLabel();
        jButtonModificar = new javax.swing.JButton();

        Fondo1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Fondo1Layout = new javax.swing.GroupLayout(Fondo1);
        Fondo1.setLayout(Fondo1Layout);
        Fondo1Layout.setHorizontalGroup(
            Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVerImgD, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );
        Fondo1Layout.setVerticalGroup(
            Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVerImgD, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Se modificó un producto de la base de datos");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¡Nuevo Cambio!");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.setBackground(new java.awt.Color(14, 14, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabelPrecioValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 187, 20));

        jLabelStockValidar.setToolTipText("");
        jPanel1.add(jLabelStockValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 187, -1));

        jPanel2.setBackground(new java.awt.Color(4, 4, 23));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(4, 4, 23));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 102), new java.awt.Color(102, 0, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 102)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MODIFICAR PRODUCTO");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/modificar_producto.png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 80));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 770, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo_jframe_1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 90));
        jPanel1.add(jLabelvalidacionNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, -1, -1));

        jPanel6.setBackground(new java.awt.Color(4, 4, 32));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCateg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCateg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCateg.setText("CATEGORIA DEL PRODUCTO");
        jLabelCateg.setVisible(false);
        jPanel6.add(jLabelCateg, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 21, -1, 29));

        jLabelNomb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNomb.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomb.setText("NOMBRE DEL PRODUCTO");
        jLabelNomb.setVisible(false);
        jPanel6.add(jLabelNomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 68, 195, 29));

        jLabelPrec.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelPrec.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrec.setText("PRECIO DEL PRODUCTO");
        jLabelPrec.setVisible(false);
        jPanel6.add(jLabelPrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 29));

        jLabelStock.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelStock.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStock.setText("STOCK DEL PRODUCTO");
        jLabelStock.setVisible(false);
        jPanel6.add(jLabelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 182, 167, 29));

        jLabelImg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelImg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImg.setText("IMAGEN DEL PRODUCTO");
        jLabelImg.setVisible(false);
        jPanel6.add(jLabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 181, 29));

        jSeparator1.setBackground(new java.awt.Color(5, 5, 61));
        jSeparator1.setForeground(new java.awt.Color(5, 5, 61));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 180, 20));

        jSeparator4.setBackground(new java.awt.Color(5, 5, 61));
        jSeparator4.setForeground(new java.awt.Color(5, 5, 61));
        jPanel6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 180, 20));

        jSeparator5.setBackground(new java.awt.Color(50, 5, 61));
        jSeparator5.setForeground(new java.awt.Color(50, 5, 61));
        jPanel6.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 20));

        jSeparator6.setBackground(new java.awt.Color(5, 5, 61));
        jSeparator6.setForeground(new java.awt.Color(5, 5, 61));
        jPanel6.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 20));

        TEXTO_MODIFICAR_PRODUCTO.setBackground(new java.awt.Color(255, 255, 255));
        TEXTO_MODIFICAR_PRODUCTO.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TEXTO_MODIFICAR_PRODUCTO.setForeground(new java.awt.Color(255, 255, 255));
        TEXTO_MODIFICAR_PRODUCTO.setText("MODIFICAR PRODUCTO");
        jPanel6.add(TEXTO_MODIFICAR_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(50, 5, 61));
        jSeparator2.setForeground(new java.awt.Color(50, 5, 61));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, 20));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 420));

        jPanel7.setBackground(new java.awt.Color(4, 4, 23));

        jLabel8.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ingrese la ID del producto a modificar");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 830, 70));

        jPanel8.setBackground(new java.awt.Color(4, 4, 32));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 102), new java.awt.Color(102, 0, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 102)));

        jButtonBuscarDatos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscarDatos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonBuscarDatos.setText("Buscar");
        jButtonBuscarDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.magenta, java.awt.Color.blue, java.awt.Color.blue, null));
        jButtonBuscarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarDatosActionPerformed(evt);
            }
        });

        jTextFieldID.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        jTextFieldID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDKeyTyped(evt);
            }
        });

        jButtonVolver.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.setVisible(false);
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jLabelID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID.setText("ID DEL PRODUCTO");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVolver)
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 630, 70));

        jPanel10.setBackground(new java.awt.Color(8, 8, 42));

        jTextFieldCateg.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jTextFieldCateg.setEnabled(false);
        jTextFieldCateg.setVisible(false);

        jTextFieldNombre.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.setVisible(false);
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyPressed(evt);
            }
        });

        jTextFieldPrecio.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jTextFieldPrecio.setBorder(null);
        jTextFieldPrecio.setVisible(false);
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });
        jTextFieldPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioKeyTyped(evt);
            }
        });

        jTextFieldStock.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jTextFieldStock.setBorder(null);
        jTextFieldStock.setVisible(false);
        jTextFieldStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStockActionPerformed(evt);
            }
        });
        jTextFieldStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldStockKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStockKeyTyped(evt);
            }
        });

        jButtonVer.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVer.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonVer.setText("Ver Imagen");
        jButtonVer.setVisible(false);
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });

        jButtonValidar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonValidar.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonValidar.setText("Validar");
        jButtonValidar.setVisible(false);
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });

        TEXTO_VALIDAR_dATOS.setBackground(new java.awt.Color(255, 255, 255));
        TEXTO_VALIDAR_dATOS.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TEXTO_VALIDAR_dATOS.setForeground(new java.awt.Color(255, 255, 255));
        TEXTO_VALIDAR_dATOS.setText("VALIDAR DATOS");
        TEXTO_VALIDAR_dATOS.setToolTipText("");

        jButtonLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setVisible(false);
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        TEXTO_LIMPIAR_DATOS.setBackground(new java.awt.Color(255, 255, 255));
        TEXTO_LIMPIAR_DATOS.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TEXTO_LIMPIAR_DATOS.setForeground(new java.awt.Color(255, 255, 255));
        TEXTO_LIMPIAR_DATOS.setText("LIMPIAR DATOS");

        jButtonModificar.setBackground(new java.awt.Color(153, 255, 153));
        jButtonModificar.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(0, 51, 0));
        jButtonModificar.setText("Modificar");
        jButtonModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 51, 0), null, new java.awt.Color(0, 51, 0)));
        jButtonModificar.setVisible(false);
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap(27, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(TEXTO_LIMPIAR_DATOS, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TEXTO_VALIDAR_dATOS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTextFieldCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButtonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXTO_VALIDAR_dATOS)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXTO_LIMPIAR_DATOS))
                .addGap(31, 31, 31))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 420, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed

        jLabelPrecioValidar.setVisible(true);
        jLabelStockValidar.setVisible(true);
        jLabelvalidacionNombre.setVisible(true);
        
           if(!jTextFieldNombre.getText().isEmpty()) {
        
            jLabelvalidacionNombre.setText("El nombre es válido");
            jLabelvalidacionNombre.setForeground(green);           
            validacionNombre = true;
            
        } else {
        
            jLabelvalidacionNombre.setText("No puede dejar el campo vacío");
            jLabelvalidacionNombre.setForeground(red);
            validacionNombre = false;            

        }
           
        if(!jTextFieldPrecio.getText().isEmpty()){
        
            validacionPrecio = true;
            jLabelPrecioValidar.setForeground(green);        
            jLabelPrecioValidar.setText("El precio es válido");
            
        } else {
        
            validacionPrecio = false;
            jLabelPrecioValidar.setForeground(red);        
            jLabelPrecioValidar.setText("No puede dejar el campo vacío");
            
        }
        
        if(!jTextFieldStock.getText().isEmpty()) {
        
            validacionStock = true;
            jLabelStockValidar.setForeground(green);        
            jLabelStockValidar.setText("El stock es válido");
            
        } else {
        
            validacionStock =false;
            jLabelStockValidar.setForeground(red);        
            jLabelStockValidar.setText("No puede dejar el campo vacío");
            
        }
        
        if(validacionNombre && validacionStock && validacionPrecio) {
        
            jButtonModificar.setVisible(true);
        
        } else {
        
            jButtonModificar.setVisible(false);
            
        }
        

    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        
        
        
        p1.setNombreProducto(jTextFieldNombre.getText());
        p1.setPrecioProducto( Integer.parseInt(jTextFieldPrecio.getText()));
        p1.setCantidadProducto(Integer.parseInt(jTextFieldStock.getText()));
        
        m2.Modificar_Producto(p1);
        
        jDialog2.setSize(464, 340);
        jDialog2.setLocation(600, 320);
        jDialog2.show();
        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        jTextFieldNombre.setText("");
        jTextFieldStock.setText("");
        jTextFieldPrecio.setText("");

        jButtonModificar.setVisible(false);
        
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonBuscarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarDatosActionPerformed
       
        int idBus = Integer.parseInt(jTextFieldID.getText());
        
        p1 = m2.Seleccionar(idBus);
         
        jTextFieldCateg.setText(p1.getCategoriaProducto());
        jTextFieldNombre.setText(p1.getNombreProducto());
        jTextFieldPrecio.setText(String.valueOf(p1.getPrecioProducto()));
        jTextFieldStock.setText(String.valueOf(p1.getCantidadProducto()));     
        
        
        jTextFieldID.setEnabled(false);
        jButtonVolver.setVisible(true);
        jLabelCateg.setVisible(true);
        jTextFieldCateg.setVisible(true);
        jLabelNomb.setVisible(true);
        jTextFieldNombre.setVisible(true);
        jLabelPrec.setVisible(true);
        jTextFieldPrecio.setVisible(true);
        jLabelStock.setVisible(true);
        jTextFieldStock.setVisible(true);
        jLabelImg.setVisible(true);
        jButtonVer.setVisible(true);
        jButtonValidar.setVisible(true);
        jButtonLimpiar.setVisible(true);
        this.TEXTO_MODIFICAR_PRODUCTO.setVisible(true);
        this.TEXTO_LIMPIAR_DATOS.setVisible(true);
        this.TEXTO_VALIDAR_dATOS.setVisible(true);
        
    }//GEN-LAST:event_jButtonBuscarDatosActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed

        jTextFieldNombre.setText("");
        jTextFieldStock.setText("");
        jTextFieldPrecio.setText("");
        
        jTextFieldID.enable(true);
        jTextFieldID.setText("");
        jButtonVolver.setVisible(false);
        jLabelCateg.setVisible(false);
        jTextFieldCateg.setVisible(false);
        jLabelNomb.setVisible(false);
        jTextFieldNombre.setVisible(false);
        jLabelPrec.setVisible(false);
        jTextFieldPrecio.setVisible(false);
        jLabelStock.setVisible(false);
        jTextFieldStock.setVisible(false);
        jLabelImg.setVisible(false);
        jButtonVer.setVisible(false);
        jButtonValidar.setVisible(false);
        jButtonLimpiar.setVisible(false);
        jButtonModificar.setVisible(false);
        jLabelvalidacionNombre.setVisible(false);
        jLabelPrecioValidar.setVisible(false);
        jLabelStockValidar.setVisible(false);

        
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextFieldPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioKeyTyped
        char k = evt.getKeyChar();

        if(!Character.isDigit(k)) {

            evt.consume();
         
        }
    }//GEN-LAST:event_jTextFieldPrecioKeyTyped

    private void jTextFieldIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDKeyTyped
 
        char k1 = evt.getKeyChar();

        if(!Character.isDigit(k1)) {

            evt.consume();
         
        }
        
    }//GEN-LAST:event_jTextFieldIDKeyTyped

    private void jTextFieldStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockKeyTyped

        char k2 = evt.getKeyChar();

        if(!Character.isDigit(k2)) {

            evt.consume();
         
        }        
        
    }//GEN-LAST:event_jTextFieldStockKeyTyped

    private void jTextFieldStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStockActionPerformed
        
        
    }//GEN-LAST:event_jTextFieldStockActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jTextFieldPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioKeyPressed
                jButtonModificar.setVisible(false);
    }//GEN-LAST:event_jTextFieldPrecioKeyPressed

    private void jTextFieldStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockKeyPressed

         jButtonModificar.setVisible(false);

    }//GEN-LAST:event_jTextFieldStockKeyPressed

    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed

        byte[] imageBytes =p1.getImagen();
        ImageIcon imageIcon = null;
        try {
            ByteArrayInputStream bais = new ByteArrayInputStream(imageBytes);
            BufferedImage imagen = ImageIO.read(bais);
            imageIcon = new ImageIcon(imagen);
        } catch (IOException e) {
            System.out.println("Error: " + e);
        }
        jDialog1.setSize(551, 387);
        jDialog1.setLocation(600, 300);
        jDialog1.show();
        jLabelVerImgD.setIcon(imageIcon); 


    }//GEN-LAST:event_jButtonVerActionPerformed

    private void jTextFieldNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyPressed
       jButtonModificar.setVisible(false);
    }//GEN-LAST:event_jTextFieldNombreKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo1;
    private javax.swing.JLabel TEXTO_LIMPIAR_DATOS;
    private javax.swing.JLabel TEXTO_MODIFICAR_PRODUCTO;
    private javax.swing.JLabel TEXTO_VALIDAR_dATOS;
    private javax.swing.JButton jButtonBuscarDatos;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCateg;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JLabel jLabelNomb;
    private javax.swing.JLabel jLabelPrec;
    private javax.swing.JLabel jLabelPrecioValidar;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JLabel jLabelStockValidar;
    private javax.swing.JLabel jLabelVerImgD;
    private javax.swing.JLabel jLabelvalidacionNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldCateg;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldStock;
    // End of variables declaration//GEN-END:variables
}
